---
name: SNMP-Extension-PassPersist
version: 0.01
author:
  - 'Sebastien Aperghis-Tramoni <sebastien@aperghis.net>'
abstract: |-
  Generic pass/pass_persist extension framework
  for Net-SNMP
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Class::Accessor: 0.30
  File::Temp: 0.12
  Getopt::Long: 2.04
  IO::File: 1.05
  IO::Handle: 1.15
  IO::Select: 1.10
  IO::String: 1.00
  List::MoreUtils: 0.21
  parent: 0.221
build_requires:
  Test::More: 0.45
recommends:
  Sort::Key::OID: 0.03
provides:
  SNMP::Extension::PassPersist:
    file: lib/SNMP/Extension/PassPersist.pm
    version: 0.01
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
